force-app/main/default/objects/Discipline_participation__c/Discipline_participation__c.object-meta.xml
<CustomObject>
    <label>Discipline participation</label>
    <nameField>
        <label>Discipline</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discipline participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discipline_participation__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipName>Departments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Exam__c/fields/Discipline__c.field-meta.xml
<CustomField>
    <fullName>Discipline__c</fullName>
    <label>Discipline</label>
    <referenceTo>Discipline_participation__c</referenceTo>
    <relationshipLabel>Exams</relationshipLabel>
    <relationshipName>Exams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>Student of my University</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Number_of_related_exams__c.field-meta.xml
<CustomField>
    <fullName>Number_of_related_exams__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Automated by Exam trigger</inlineHelpText>
    <label>Number of related exams</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExamCalculationFuture.cls
public without sharing class ExamCalculationFuture {

    @future
    public static void recalculateExams() {   
        Set<Id> StudentIdSet = new Set<Id>();
        
        for (Discipline_participation__c participation: [SELECT Student__c FROM Discipline_participation__c]){
            StudentIdSet.add(participation.Student__c);
        }
        
        List<Student__c> studentsToUpdateList = new List<Student__c>();
        List<AggregateResult> groupedResults = [
            SELECT Discipline__r.Student__c student, COUNT(Id) exams 
            FROM Exam__c WHERE Active__c = TRUE AND Discipline__r.Student__c IN :StudentIdSet 
            GROUP BY Discipline__r.Student__c];
        
        for (AggregateResult ar : groupedResults) {
            Id studentId = (Id)ar.get('student');
            Integer count = (Integer)ar.get('exams');
            Student__c student = new Student__c(Id = studentId, Number_of_related_exams__c = count);
            studentsToUpdateList.add(student);
        }

        if(!studentsToUpdateList.isEmpty()){
            update studentsToUpdateList;
        }
    }
}