force-app/main/default/objects/Discipline_participation__c/Discipline_participation__c.object-meta.xml
<CustomObject>
    <label>Discipline participation</label>
    <nameField>
        <label>Discipline</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discipline participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discipline_participation__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipName>Departments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Exam__c/fields/Discipline__c.field-meta.xml
<CustomField>
    <fullName>Discipline__c</fullName>
    <label>Discipline</label>
    <referenceTo>Discipline_participation__c</referenceTo>
    <relationshipLabel>Exams</relationshipLabel>
    <relationshipName>Exams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>Student of my University</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Number_of_related_exams__c.field-meta.xml
<CustomField>
    <fullName>Number_of_related_exams__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Automated by Exam trigger</inlineHelpText>
    <label>Number of related exams</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DailyExamCalculationBatch.cls
public class DailyExamCalculationBatch implements Database.Batchable<sObject>, Database.Stateful, Schedulable {

    // '0 minute, 8 hour, * day, * month, * dayweek ' - daily start at 8 o`clock
    // System.Schedule('calculate number of Exams', '0 8 * * *  ? ',new DailyExamCalculationBatch());
    
    public void execute(SchedulableContext sc) {
        DailyExamCalculationBatch dailyExamCalculationBatch = new DailyExamCalculationBatch(); 
        Database.executeBatch(dailyExamCalculationBatch, 200);
    }

    Map<Id, Integer> studentIdToExamsNumberMap = new Map<Id, Integer>();
    List<Student__c> studentsToUpdateList = new List<Student__c>();

    public Database.QueryLocator start(Database.BatchableContext bc) {
        // Fetch all Active Exam records
        String query = 'SELECT Id, Active__c, Discipline__r.Student__r.Id, Discipline__r.Student__r.Number_of_related_exams__c FROM Exam__c WHERE Active__c = TRUE';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Exam__c> scope) {
        // Calculate relatedNumbers and put result to the studentIdToExamsNumberMap for each Student
        for(Exam__c exam : scope){
            Id studentId = exam.Discipline__r.Student__r.Id;

            if (studentIdToExamsNumberMap.get(studentId) == null) {
                studentIdToExamsNumberMap.put(studentId, 1);
            } else {
                Integer relatedNumbers = studentIdToExamsNumberMap.get(studentId);
                studentIdToExamsNumberMap.put(studentId, relatedNumbers++);
            }
        }
    }
  
    public void finish(Database.BatchableContext bc){
        for(Id studentId : studentIdToExamsNumberMap.keyset()){
            Student__c student = new Student__c(Id = studentId, Number_of_related_exams__c = studentIdToExamsNumberMap.get(studentId));
            studentsToUpdateList.add(student);
        }

        if(!studentsToUpdateList.isEmpty()){
            update studentsToUpdateList;
        }
    }  
}