force-app/main/default/objects/Discipline_participation__c/Discipline_participation__c.object-meta.xml
<CustomObject>
    <label>Discipline participation</label>
    <nameField>
        <label>Discipline</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discipline participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discipline_participation__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipName>Departments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Exam__c/fields/Discipline__c.field-meta.xml
<CustomField>
    <fullName>Discipline__c</fullName>
    <label>Discipline</label>
    <referenceTo>Discipline_participation__c</referenceTo>
    <relationshipLabel>Exams</relationshipLabel>
    <relationshipName>Exams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>Student of my University</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Number_of_related_exams__c.field-meta.xml
<CustomField>
    <fullName>Number_of_related_exams__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Automated by Exam trigger</inlineHelpText>
    <label>Number of related exams</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExamTriggerHandler.cls
public with sharing class ExamTriggerHandler {
    public static void updateParentStudent(Map<Id, Exam__c> newMap, Map<Id, Exam__c> oldMap){
        Map<Id, Integer> studentIdToExamsNumberMap = new Map<Id, Integer>();
        List<Student__c> studentsToUpdateList = new List<Student__c>();

        Set<Id> examIdSet = new Set<Id>();
        if (Trigger.isDelete) {
            examIdSet = oldMap.keySet();
        } else {
            examIdSet = newMap.keySet();
        }

        //Fetch Exam__c records width needed fields by Id and Active__c = TRUE
        List<Exam__c> examList = [
            SELECT Id, Active__c, Discipline__r.Student__r.Id, Discipline__r.Student__r.Number_of_related_exams__c 
            FROM Exam__c 
            WHERE Id IN : examIdSet];

        // Calculate relatedNumbers and put result to the studentIdToExamsNumberMap for each Student
        for(Exam__c exam : examList){
            Id studentId = exam.Discipline__r.Student__r.Id;
            Integer relatedNumbers = (Integer)exam.Discipline__r.Student__r.Number_of_related_exams__c;
            
            // Needs only for Update check condition
            if(exam.Active__c == true){
                if (Trigger.isInsert || Trigger.isUndelete || Trigger.IsUpdate && oldMap.get(exam.Id).Active__c == false) {
                    relatedNumbers ++;
                } else if (Trigger.isDelete) {
                    relatedNumbers --;
                } 
            } else if (Trigger.IsUpdate && oldMap.get(exam.Id).Active__c == true) {
                relatedNumbers --;
            }

            if (relatedNumbers < 0) {
                throw new MyException('Something went wrong, relatedNumbers = ' + relatedNumbers);
            }
            studentIdToExamsNumberMap.put(studentId, relatedNumbers);
        }

        // Check Number of related exams and if value was changed add it to List for update
        for(Exam__c exam : examList){
            Id studentId = exam.Discipline__r.Student__r.Id;
            Integer newValue = studentIdToExamsNumberMap.get(studentId);
            Integer oldValue = (Integer)exam.Discipline__r.Student__r.Number_of_related_exams__c;
            if(oldValue != newValue){
                Student__c student = new Student__c(Id = studentId, Number_of_related_exams__c = newValue);
                studentsToUpdateList.add(student);
            }
        }

        if(!studentsToUpdateList.isEmpty()){
            update studentsToUpdateList;
        }
    }
    public class MyException extends Exception {}
}