force-app/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Exam__c/fields/Discipline__c.field-meta.xml
<CustomField>
    <fullName>Discipline__c</fullName>
    <label>Discipline</label>
    <referenceTo>Discipline_participation__c</referenceTo>
    <relationshipLabel>Exams</relationshipLabel>
    <relationshipName>Exams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Exam__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <inlineHelpText>Please enter rating from 1 to 12</inlineHelpText>
    <label>Rating</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>Student of my University</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Number_of_related_exams__c.field-meta.xml
<CustomField>
    <fullName>Number_of_related_exams__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Automated by Exam trigger</inlineHelpText>
    <label>Number of related exams</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExamTriggerHandlerTest.cls
@isTest
private class ExamTriggerHandlerTest {
    @TestSetup
    static void makeData(){
        TestDataFactory.makeData();
    }

    @isTest
    private static void testInsertExam() {
        // Actual test
        Test.startTest();
        insert new Exam__c(Name = 'Test Insert Exam', Rating__c= 10, Active__c = true, Discipline__c = dp.Id);
        Test.stopTest();

        // Asserts
        Student__c student = [SELECT Id, Number_of_related_exams__c FROM Student__c LIMIT 1]; 
        System.assertEquals(2, student.Number_of_related_exams__c, 'Expected 1 Exam in calc');
    }

    @isTest
    private static void testUpdateExam(){
        insert new Exam__c(Name = 'Test Exam2', Rating__c= 5, Active__c = true, Discipline__c = dp.Id);

        // Actual test
        Test.startTest();
        Exam__c exam = [SELECT Id, Name, Active__c FROM Exam__c WHERE Name = 'Test Exam'];
        exam.Active__c = false;
        update exam;
        Test.stopTest();

        // Asserts
        Student__c student = [SELECT Id, Number_of_related_exams__c FROM Student__c LIMIT 1]; 
        System.assertEquals(1, student.Number_of_related_exams__c, 'Expected 0 Exam in calc');
    }

    @isTest
    private static void testDeleteExam(){

        // Actual test
        Test.startTest();
        Exam__c exam = [SELECT Id, Name, Active__c FROM Exam__c WHERE Name = 'Test Exam'];
        delete exam;
        Test.stopTest();

        // Asserts
        Student__c student = [SELECT Id, Number_of_related_exams__c FROM Student__c LIMIT 1]; 
        System.assertEquals(0, student.Number_of_related_exams__c, 'Expected 0 Exam in calc');
    }

}