force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <inlineHelpText>Enter value from 1 to 5</inlineHelpText>
    <label>Rating</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <label>Teacher</label>
    <referenceTo>Teacher__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Teacher__c/Teacher__c.object-meta.xml
<CustomObject>
    <description>Teachers of University</description>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ReviewTriggerHandlerTest.cls
@isTest
private class ReviewTriggerHandlerTest {
    @TestSetup
    static void makeData(){
        TestDataFactory.makeData();
    }

    @isTest
    private static void testRatingValidationLess() {
        // Actual test
        Test.startTest();
        insert new Review__c(Teacher__c = t.Id, Rating__c = 0);
        Test.stopTest();

        Review__c review = [SELECT Id, Rating__c FROM Review__c LIMIT 1];
        // Asserts
        System.assertEquals(1, review.Rating__c, 'Expecting rating was fixed from 0 to 1');
    }

    @isTest
    private static void testRatingValidationGreates() {
        // Actual test
        Test.startTest();
        insert new Review__c(Teacher__c = t.Id, Rating__c = 9);
        Test.stopTest();

        Review__c review = [SELECT Id, Rating__c FROM Review__c LIMIT 1];
        // Asserts
        System.assertEquals(5, review.Rating__c, 'Expecting rating was fixed from 9 to 5');
    }
}