force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>Student of my University</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Number_of_related_exams__c.field-meta.xml
<CustomField>
    <fullName>Number_of_related_exams__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Automated by Exam trigger</inlineHelpText>
    <label>Number of related exams</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExamCalculationFutureTest.cls
@isTest
private class ExamCalculationFutureTest {
    @TestSetup
    static void makeData(){
        TestDataFactory.makeData();
    }

    @isTest
    private static void testRecalculateExams() {
        // Actual test
        Test.startTest();
        ExamCalculationFuture.recalculateExams();
        Test.stopTest();

        // Asserts
        Student__c student = [SELECT Id, Number_of_related_exams__c FROM Student__c LIMIT 1]; 
        System.assertEquals(1, student.Number_of_related_exams__c, 'Expected 1 Exam in calc');
    }

}